<?php
/*
mysqli = clase de mysql para trabajar con base de datos
PDO = OBJETOS DE DATOS DE PHP
PHP DATA OBJECT
PDO TIENE MAYOR SEGURIDAD
PROTEJE DE SQL INJECTION
PDO SOLO MANEJA CONECCION, NO EJECUTA SCRIPT SQL
PDO PREPARA LAS CONSULTAS SQLS
PDO RETORNA UN OBJETO PDOSTATEMENT
*/
